---
# Per environment values which override defaults in hmpps-official-visits-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: official-visits-api-dev.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: dev
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    API_BASE_URL_HMPPS_AUTH: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_LOCATIONS_INSIDE_PRISON: "https://locations-inside-prison-api-dev.hmpps.service.justice.gov.uk"
    API_BASE_URL_MANAGE_USERS: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    API_BASE_URL_PRISONER_SEARCH: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    API_BASE_URL_PERSONAL_RELATIONSHIPS: "https://personal-relationships-api-dev.hmpps.service.justice.gov.uk"

  allowlist:
    groups:
      - internal
      - prisons
      - moj_cloud_platform
      - digital_staff_and_mojo

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: move-and-improve-alerts-non-prod
